### ISSUE TITLE
Add spell check to the test doc

### ISSUE THREAD

**Issue by epiccurious** [epiccurious/bitcoin-core-node-builder#133]
Need to figure out a way to reduce false-positives such as "sudo" but it helped me find a spelling mistake in "Inspriation"

So it's probably worthwhile to recommend for markdown changes.

Requires a `.pyspelling.yaml` that should contain something like:
```yaml
matrix:
- name: Python Source
  aspell:
    lang: en
    d: en_US
  sources:
  - /home/user1/Documents/GitHub/bitcoin-core-node-builder/*.md
```
